Project:
  Name: my-new-project-1234
  Description: description
  Visibility: public
  Category: Web Development
  Subcategory: Frontend
  Tags: []
  View:
    Mode: dynamic
Owner:
  Username: herogautam
  ProfileURL: https://github.com/herogautam
Metadata:
  CreatedAt: 2025-07-15T14:47:36.602Z
  LastUpdated: 2025-07-15T14:47:36.602Z
  Version: 1.0.0
Features: []
Dependencies:
  CSS: []
  JS: []
Licensing:
  Type: MIT
  Link: https://opensource.org/licenses/MIT
Community:
  AllowFork: true
  AllowComment: true
  AllowRemix: true