Project:
  Id: 80ba93e6-7c12-4dd8-bef5-8373e15e6c8e
  Name: test-pro-4
  Slug: test-pro-4
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: gautamankoji
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-04T10:25:21.339Z
  UpdatedAt: 2025-08-04T10:25:21.339Z
  Version: 1.0.0