Project:
  Id: f5ed951e-1d3d-48fc-832a-42cd0b822e0f
  Name: Remix of Remix of Remix of Remix of Remix of Remix of testing1
  Slug: remix-of-remix-of-remix-of-remix-of-remix-of-remix-of-testing1
  Description: test
  Visibility: public
  Category: web development
  Tags: []
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: 91d154c0-8728-4324-9596-f689b92081d7
Owner:
  Username: herogautam
  ProfileUrl: https://github.com/herogautam
Metadata:
  CreatedAt: 2025-07-27T12:45:09.850Z
  UpdatedAt: 2025-07-27T12:45:09.850Z
  Version: 1.0.0