Project:
  Id: f2975bc5-0d7b-462b-9e73-e2688a11e163
  Name: testing-1
  Slug: testing-1
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: gautamankoji
  UserId: 6649dd0f-273f-4892-bb28-697bd3cac8c3
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-06T19:50:29.033Z
  UpdatedAt: 2025-08-06T19:50:29.033Z
  Version: 1.0.0