Project:
  Id: 88487edc-75ee-4ab4-9073-f3127fb8a852
  Name: Remix of Remix of Remix of Remix of testing1
  Slug: remix-of-remix-of-remix-of-remix-of-testing1
  Description: test
  Visibility: public
  Category: web development
  Tags: []
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: 852b99c6-5301-4fd4-8eee-8474e80c8fd6
Owner:
  Username: herogautam
  ProfileUrl: https://github.com/herogautam
Metadata:
  CreatedAt: 2025-07-27T12:43:46.622Z
  UpdatedAt: 2025-07-27T12:43:46.622Z
  Version: 1.0.0