Project:
  Id: be2a0304-d3ff-426d-8bd6-b71bd97b9b3f
  Name: new-button
  Slug: new-button
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: herogautam
  UserId: 3de3e775-7cf8-4911-9359-e8debf12e3c9
  Name: Hero Gautam
  avatarUrl: https://avatars.githubusercontent.com/u/104679794?v=4
Metadata:
  CreatedAt: 2025-08-06T18:45:26.450Z
  UpdatedAt: 2025-08-06T18:45:26.450Z
  Version: 1.0.0