Project:
  Id: 8360deae-6aa5-432d-a618-da5f6ea0d91f
  Name: Correct Remix of Aurora Landing by herogautam
  Slug: correct-remix-of-aurora-landing-by-herogautam
  Description: A sleek and responsive landing page template designed with modern layout principles and animated interactions.
  Visibility: public
  Category: ui component
  Tags:
    - landing
    - responsive
    - animated
    - hero
    - modern
    - ui
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: herogautam-landing-page-1753704048550
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-28T12:08:13.137Z
  UpdatedAt: 2025-07-28T12:08:13.137Z
  Version: 1.0.0