Project:
  Id: ca11f850-28f4-4db4-9fa2-d1c03e6578fd
  Name: test-pro-3
  Slug: test-pro-3
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: gautamankoji
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-04T10:18:34.156Z
  UpdatedAt: 2025-08-04T10:18:34.156Z
  Version: 1.0.0