Project:
  Id: ce05a153-0dfd-493e-8398-ad9f3cc9955d
  Name: sfssdfsdf
  Slug: sfssdfsdf
  Description: ""
  Visibility: private
  Category: button
  Tags: []
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-26T21:29:49.898Z
  UpdatedAt: 2025-07-26T21:29:49.898Z
  Version: 1.0.0