Project:
  Id: 923cc191-cba7-40c6-ab2f-c89f1cbf8a7b
  Name: Blue Button by herogautam
  Slug: blue-button-by-herogautam
  Description: A project preview.
  Visibility: public
  Category: web
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: herogautam-button-1753864532717
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-30T08:35:55.757Z
  UpdatedAt: 2025-07-30T08:35:55.757Z
  Version: 1.0.0