Project:
  Id: f45e39eb-4375-4ec2-950f-7e9f9fd806c9
  Name: test-pro-05
  Slug: test-pro-05
  Description: A sleek and responsive landing page template designed with modern layout principles and animated interactions.
  Visibility: public
  Category: ui component
  Tags:
    - landing
    - responsive
    - animated
    - hero
    - modern
    - ui
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
  RemixOf: herogautam-landing-page-1754303804960
Owner:
  Username: gautamankoji
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-04T10:36:53.199Z
  UpdatedAt: 2025-08-04T10:36:53.199Z
  Version: 1.0.0