Project:
  Name: my-user-project
  Description: nice description
  Visibility: public
  Category: Web Development
  Subcategory: Frontend
  Tags: []
  View:
    Mode: dynamic
Owner:
  Username: mosaicra-bot
  ProfileURL: https://github.com/mosaicra-bot
Metadata:
  CreatedAt: 2025-07-12T20:30:33.855Z
  LastUpdated: 2025-07-12T20:30:33.856Z
  Version: 1.0.0
Features: []
Dependencies:
  CSS: []
  JS: []
Licensing:
  Type: MIT
  Link: https://opensource.org/licenses/MIT
Community:
  AllowFork: true
  AllowComment: true
  AllowRemix: true