Project:
  Id: 6fe406d9-4ad1-497b-a965-4068c97225d6
  Name: Remix of Aurora Landing
  Slug: remix-of-aurora-landing
  Description: A sleek and responsive landing page template designed with modern layout principles and animated interactions.
  Visibility: public
  Category: ui component
  Tags:
    - landing
    - responsive
    - animated
    - hero
    - modern
    - ui
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: herogautam-landing-page-1753630360472
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-27T15:33:07.359Z
  UpdatedAt: 2025-07-27T15:33:07.359Z
  Version: 1.0.0