Project:
  Name: Untitled Project
  Description: A project preview.
  Visibility: public
  Category: Web
  Subcategory: General
  Tags: []
  View:
    Mode: dynamic
Owner:
  Username: play
  ProfileURL: https://github.com/play
Metadata:
  CreatedAt: 2025-07-20T15:21:14.467Z
  LastUpdated: 2025-07-20T15:21:20.759Z
  Version: 1.0.0
Features: []
Dependencies:
  CSS: []
  JS: []
Licensing:
  Type: MIT
  Link: https://opensource.org/licenses/MIT
Community:
  AllowFork: true
  AllowComment: true
  AllowRemix: true