Project:
  Name: testing-proeject-01
  Description: description
  Visibility: public
  Category: Desktop App
  Subcategory: Tauri
  Tags: []
  View:
    Mode: dynamic
Owner:
  Username: herogautam
  ProfileURL: https://github.com/herogautam
Metadata:
  CreatedAt: 2025-07-13T07:15:39.728Z
  LastUpdated: 2025-07-13T07:15:39.728Z
  Version: 1.0.0
Features: []
Dependencies:
  CSS: []
  JS: []
Licensing:
  Type: MIT
  Link: https://opensource.org/licenses/MIT
Community:
  AllowFork: true
  AllowComment: true
  AllowRemix: true