Project:
  Id: a085b907-81fd-422a-973c-82826f853911
  Name: new-button
  Slug: new-button
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: gautamankoji
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-06T17:28:54.690Z
  UpdatedAt: 2025-08-06T17:28:54.690Z
  Version: 1.0.0