Project:
  Id: e98462dc-5a32-4e7e-bf32-9e9d926b4ca0
  Name: Variant ii of my-test-pro-4
  Slug: variant-ii-of-my-test-pro-4
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
  VariantOfId: 1d9a46fa-dd93-4980-8897-78764ac3acd8
Owner:
  Username: mosaicra-creator
  Name: null
  avatarUrl: https://avatars.githubusercontent.com/u/220522994?v=4
Metadata:
  CreatedAt: 2025-08-04T15:11:52.285Z
  UpdatedAt: 2025-08-04T15:11:52.285Z
  Version: 1.0.0