Project:
  Name: "Aurora Landing"
  Description: "A sleek and responsive landing page template designed with modern layout principles and animated interactions."
  Visibility: "public"  # options: public | private
  Category: "UI Component"
  Subcategory: "Landing Page"
  Tags:
    - landing
    - responsive
    - animated
    - hero
    - modern
    - ui

  View:
    Mode: "dynamic"  # options: dynamic | image

  Owner:
    Username: "herogautam"
    ProfileURL: "https://github.com/herogautam"

  Metadata:
    CreatedAt: "2025-07-08T02:45:00+05:30"
    LastUpdated: "2025-07-08T02:45:00+05:30"
    Version: "1.0.0"

  Features:
    - ResponsiveLayout
    - AnimatedSections
    - ScrollAware
    - CleanTypography

  Dependencies:
    CSS:
      - "tailwindcss"
    JS:
      - "vanilla"

  Licensing:
    Type: "MIT"
    Link: "https://opensource.org/licenses/MIT"

  Community:
    AllowFork: true
    AllowComment: true
    AllowRemix: true
