Project:
  Id: 9e12c633-0b6d-40a0-b9e6-b36af8b059be
  Name: button
  Slug: button
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: gautamankoji
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-06T17:07:45.200Z
  UpdatedAt: 2025-08-06T17:07:45.200Z
  Version: 1.0.0