Project:
  Name: Blue Button
  Description: A project preview.
  Visibility: public
  Category: Web
  Subcategory: Button
  Tags: []
  View:
    Mode: dynamic
Owner:
  Username: gautamankoji
  ProfileURL: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-10T09:33:00.354Z
  LastUpdated: 2025-07-10T09:33:11.775Z
  Version: 1.0.0
Features: []
Dependencies:
  CSS: []
  JS: []
Licensing:
  Type: MIT
  Link: https://opensource.org/licenses/MIT
Community:
  AllowFork: true
  AllowComment: true
  AllowRemix: true