Project:
  Id: e44dd928-de88-43a7-a7b0-15ff50f7aaf0
  Name: Remix of Variant ii of my-test-pro-4
  Slug: remix-of-variant-ii-of-my-test-pro-4
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
  RemixOfId: e98462dc-5a32-4e7e-bf32-9e9d926b4ca0
Owner:
  Username: gautamankoji
  Name: Gautam Ankoji
  avatarUrl: https://avatars.githubusercontent.com/u/120157430?v=4
Metadata:
  CreatedAt: 2025-08-04T15:18:57.569Z
  UpdatedAt: 2025-08-04T15:18:57.569Z
  Version: 1.0.0