Project:
  Id: a8dce41d-4883-40fe-8815-a8f4a6e55a31
  Name: my-new-project
  Slug: my-new-project
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-26T07:37:05.143Z
  UpdatedAt: 2025-07-26T07:37:05.143Z
  Version: 1.0.0