Project:
  Id: c5974152-dfe1-4113-9c3b-442e02f0c932
  Name: Remix of testing
  Slug: remix-of-testing
  Description: test
  Visibility: public
  Category: web development
  Tags: []
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: herogautam-testing-1753619952812
Owner:
  Username: herogautam
  ProfileUrl: https://github.com/herogautam
Metadata:
  CreatedAt: 2025-07-27T12:40:09.187Z
  UpdatedAt: 2025-07-27T12:40:09.187Z
  Version: 1.0.0