Project:
  Id: c216006e-b7be-4e98-8f23-cdcb425077a4
  Name: testing-3
  Slug: testing-3
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowDiscussions: true
Owner:
  Username: herogautam
  UserId: 3de3e775-7cf8-4911-9359-e8debf12e3c9
  Name: Hero Gautam
  avatarUrl: https://avatars.githubusercontent.com/u/104679794?v=4
Metadata:
  CreatedAt: 2025-08-06T18:57:27.854Z
  UpdatedAt: 2025-08-06T18:57:27.854Z
  Version: 1.0.0