Project:
  Id: e2ef156f-39a9-4478-9ca9-875718fd1e26
  Name: Landing Page 02
  Slug: landing-page-02
  Description: A sleek and responsive landing page template designed with modern layout principles and animated interactions.
  Visibility: public
  Category: ui component
  Tags:
    - landing
    - responsive
    - animated
    - hero
    - modern
    - ui
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: herogautam-landing-page-1753897946988
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-30T18:34:49.393Z
  UpdatedAt: 2025-07-30T18:34:49.393Z
  Version: 1.0.0