Project:
  Name: testing-project
  Description: Description
  Visibility: public
  Category: Data Science
  Subcategory: Analytics
  Tags: []
  View:
    Mode: dynamic
Owner:
  Username: herogautam
  ProfileURL: https://github.com/herogautam
Metadata:
  CreatedAt: 2025-07-13T05:14:11.054Z
  LastUpdated: 2025-07-13T05:14:11.055Z
  Version: 1.0.0
Features: []
Dependencies:
  CSS: []
  JS: []
Licensing:
  Type: MIT
  Link: https://opensource.org/licenses/MIT
Community:
  AllowFork: true
  AllowComment: true
  AllowRemix: true