Project:
  Id: 6c7b9e7c-6cf2-4df0-a6d0-fb1975f26409
  Name: test-remix-01
  Slug: test-remix-01
  Description: A sleek and responsive landing page template designed with modern layout principles and animated interactions.
  Visibility: public
  Category: ui component
  Tags:
    - landing
    - responsive
    - animated
    - hero
    - modern
    - ui
  ViewMode: dynamic
  Interface: web
  Language: html
  Framework: none
  Styling:
    Type: css
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
  RemixOf: herogautam-landing-page-1754195556667
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-08-03T04:33:06.128Z
  UpdatedAt: 2025-08-03T04:33:06.128Z
  Version: 1.0.0