Project:
  Id: eejv0sz47
  Name: hello
  Slug: hello
  Description: ""
  Visibility: public
  Category: button
  Tags: []
  ViewMode: Dynamic
  Interface: Web
  Language: HTML
  Framework: None
  Styling:
    Type: CSS
    Libraries: []
  Licensing:
    Type: MIT
    Link: https://opensource.org/licenses/MIT
  Community:
    AllowRemix: true
    AllowComment: true
Owner:
  Username: gautamankoji
  ProfileUrl: https://github.com/gautamankoji
Metadata:
  CreatedAt: 2025-07-26T06:41:05.158Z
  UpdatedAt: 2025-07-26T06:41:05.158Z
  Version: 1.0.0
  LastUpdated: 2025-07-26T06:41:05.158Z