name: Update Supabase Project Index

on:
  push:
    paths:
      - 'u/**/mosaicra.config.yaml'

jobs:
  update-project-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Parse updated config and update Supabase
        run: |
          import os, yaml, requests, glob
          from pathlib import Path
          from datetime import datetime
          import json

          SUPABASE_URL = os.environ['SUPABASE_URL']
          SUPABASE_KEY = os.environ['SUPABASE_SERVICE_ROLE']

          def iso_now():
              return datetime.utcnow().isoformat() + 'Z'

          headers = {
              "apikey": SUPABASE_KEY,
              "Authorization": f"Bearer {SUPABASE_KEY}",
              "Content-Type": "application/json"
          }

          config_paths = glob.glob("u/*/*/mosaicra.config.yaml")

          for path in config_paths:
              with open(path) as f:
                  config = yaml.safe_load(f)

              parts = Path(path).parts
              username = parts[1]
              project_name = parts[2]

              payload = {
                  "project_id": config.get("projectId"),
                  "name": config.get("name", project_name),
                  "slug": config.get("slug", project_name.lower().replace(' ', '-')),
                  "description": config.get("description"),
                  "category": config.get("category"),
                  "interface": config.get("interface", "web"),
                  "visibility": config.get("visibility", "public"),
                  "version": config.get("version"),
                  "tags": config.get("tags", []),
                  "owner_username": username,
                  "updated_at": iso_now()
              }

              url = f"{SUPABASE_URL}/rest/v1/project_index?project_id=eq.{payload['project_id']}"

              res = requests.get(url, headers=headers)
              if res.ok and res.json():
                  # Update
                  requests.patch(url, headers=headers, data=json.dumps(payload))
              else:
                  # Insert
                  payload["created_at"] = iso_now()
                  requests.post(f"{SUPABASE_URL}/rest/v1/project_index", headers=headers, data=json.dumps(payload))
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
